app:
  title: 'Phalcon Documentation'
  name: 'Phalcon Documentation'
  author: 'Phalcon Team'
  description: 'Official Phalcon Documentation'
  keywords: 'php, phalcon, phalcon php, php framework, faster php framework, php extension, next generation framework, docs, documentation'
  email: 'team@phalcon.io'
  facebook:
  github: 'phalcon'
  rss: 'phalcon'
  twitter: 'phalconphp'
  analytics: 'UA-133802124-5'
  language: 'en'
  version: '3.4'
  comments: false

permalink: :title

url: https://docs.phalcon.io

include:
  - _redirects
  - sitemap.xml

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
  auto_ids: true
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Exclude these files from our production _site
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - updateData.sh
  - serve
  - netlify.toml
  - boxfile.yml



